name: Build Docker

on:
  push:
    branches:
      - main #只在main推送时执行
  pull_request:
    branches:
      - main

jobs:
  build: # 原本Hyperf自带的作业
    runs-on: centos-8.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cp -rf .github/workflows/Dockerfile . && docker build -t hyperf .

  deploy:
    runs-on: centos-8.2
    needs: build # 要求上一个作业完成
    steps:
      - uses: actions/checkout@v2
      - name: pull code
        uses: appleboy/ssh-action@master
        env:
          SERVER_WORKDIR: ${{ secrets.SERVER_WORKDIR }} #传递工作目录变量
        with:
          host: ${{ secrets.SERVER_HOST }} #服务器地址
          username: ${{ secrets.SERVER_USERNAME }} #用户名
          key: ${{ secrets.SERVER_KEY }} #私钥 安全问题一定都以变量的方式传递！！！
          envs: SERVER_WORKDIR #使用工作目录变量
          # 进入到项目目录，执行依赖更新
          script: |
            cd $SERVER_WORKDIR #进入到工作目录
            git checkout . #丢弃修改
            git pull #拉取代码
            composer update #更新依赖
            sudo supervisorctl restart emo #重启项目
