name: Build Docker

on:
  push:
    branches:
      - main #只在main推送时执行
  pull_request:
    branches:
      - main

env:
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  USER_NAME: ${{ secrets.SERVER_USERNAME }} # 服务器用户名
  WORK_DIR: ${{ secrets.SERVER_WORKDIR }}

# easingthemes/ssh-deploy@v2.0.7
#  env:
#    # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
#    SSH_PRIVATE_KEY: ${{ secrets.TOKEN }}
#    # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
#    ARGS: "-avzr --delete"
#    # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
#    SOURCE: "dist/"
#    # 服务器域名
#    REMOTE_HOST: "49.233.195.71"
#    # 腾讯云默认用户名为root
#    REMOTE_USER: "root"
#    # 目标目录
#    TARGET: "/usr/share/nginx/html"
#
#  作者：喂。小欢
#  链接：https://juejin.cn/post/6844903822800732167
#  来源：稀土掘金
#  著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.USER_NAME }}
          key: ${{ env.SERVER_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.WORK_DIR }}
            git pull
            docker-compose up -d --build